### ISSUE TITLE
UnicodeEncodeError - Ascii conversion fails (presumably emoji)

### ISSUE THREAD

**Issue by Kkevsterrr** [Kkevsterrr/learning_twitter#5]
"UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-12: ordinal not in range(128)"

Presumed emoji in tweet crashes ascii conversion.

**Comment by cmrfrd** [comment]
Yes emoji's cause a Unicode Error. There are so many emoji's I tried substituting some of them from 148-153 (try except block) but there are too many to eliminate so bug fix is to only except alphanumeric characters and classify all others as emoji's. with some special character

**Comment by cmrfrd** [comment]
Fixed issue, added unicode filter. Didn't get any errors in the 10 times I ran it so I think it's good
